name: frontend
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  fl_chart: ^1.1.1
  http: ^1.1.0
  flutter_secure_storage: ^9.2.4
  provider: ^6.0.0
  font_awesome_flutter: ^10.6.0
  shared_preferences: ^2.3.2
  table_calendar: ^3.0.9
  speech_to_text: ^7.0.0
  video_player: ^2.8.5
  google_generative_ai: ^0.4.3
  share_plus: ^12.0.1
  pdf: ^3.10.4
  google_maps_flutter: ^2.2.3
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  latlong2: ^0.9.0
  url_launcher: ^6.1.11
  image_picker: ^1.0.4
  dropdown_search: ^6.0.2
  file_picker: ^10.3.3
  path_provider: ^2.1.1
  open_file: ^3.5.7
  permission_handler: ^12.0.1
  cupertino_icons: ^1.0.8
  path: ^1.8.3
  syncfusion_flutter_calendar: ^31.2.5
  connectivity_plus: ^7.0.0
  timeago: ^3.7.0

  firebase_core: ^3.15.2
  firebase_messaging: ^15.2.10
  flutter_local_notifications: ^19.5.0
  cloud_firestore: ^5.6.12
  firebase_auth: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

dependency_overrides:
  firebase_messaging_web: ^3.7.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
